Add hybrid pro to device selector python window
GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD pull request #586
Opened 2022-10-11 11:11 UTC by Vsevolod1983

### PURPOSE
Add "hybrid pro" option to device selector python window

### EFFECT OF CHANGE
When you open device configuration window "HybridPro" option appears

2022-10-17 08:59 UTC, bnagirniak approved these changes

2022-10-17 14:46 UTC, s1lentssh requested changes

2022-10-17 14:46 UTC, s1lentssh commented on pxr/imaging/rprUsd/devicesConfiguration.py
> +    def __init__(self, configuration, show_restart_warning, isModal):
Please use PEP8 naming convention, e.g. is_modal

2022-10-17 14:46 UTC, s1lentssh commented on pxr/imaging/rprUsd/devicesConfiguration.py
> +        if isModal:
Please use PEP8 naming convention, e.g. is_modal

2022-10-17 14:46 UTC, s1lentssh commented on pxr/imaging/rprUsd/devicesConfiguration.py
> +def open_window(parent=None, parent_flags=QtCore.Qt.Widget, show_restart_warning=True, isModal=False):
Please use PEP8 naming convention, e.g. is_modal

2022-10-17 14:46 UTC, s1lentssh commented on pxr/imaging/rprUsd/devicesConfiguration.py
> +    dialog = _DevicesConfigurationDialog(configuration, show_restart_warning, isModal)
Please use PEP8 naming convention, e.g. is_modal

2022-10-19 09:47 UTC, s1lentssh approved these changes

2022-10-19 20:45 UTC, merged