profile output
GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD pull request #615
Opened 2022-12-15 22:37 UTC by dmitrii-z

### PURPOSE
Added rendering time output to use in autotests

2022-12-30 09:14 UTC, Vsevolod1983 requested changes
I would prefer to have such output on plugin side, not on hdRPR side.
We have RenderStats which can be filled, like we do it for another render statistics. And this RenderStats can be read from a plugin.

2023-01-07 00:34 UTC, bsavery commented
@Vsevolod1983  We do need profile for running standalone though,

2023-01-11 13:32 UTC, Vsevolod1983 approved these changes

2023-01-11 14:04 UTC, Vsevolod1983 commented
hmm, ok, I see. But I would split business logic and log output somehow though

2023-02-17 16:41 UTC, merged