Fsr2
GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD pull request #659
Opened 2023-04-23 20:04 UTC by dmitrii-z

### PURPOSE
FSR2 support
Resolves: https://amdrender.atlassian.net/browse/RPRUS-157, https://amdrender.atlassian.net/browse/RPRHOUD-53

2023-04-25 14:24 UTC, ARozghon commented
Approved by QA

2023-04-27 12:25 UTC, DagerD approved these changes
Code looks ok. One note in comments.

2023-04-27 12:25 UTC, DagerD commented on pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
> +                    if setting['name'] == 'core:renderQuality':
can it be simplified like this?
`viewport_render_setting_categories = (category for category in render_setting_categories \`
`        if category['name'] in ('RenderQuality', 'Sampling', 'AdaptiveSampling', 'Denoise', 'ViewportSettings'))`
`for category in (cat for cat in viewport_render_setting_categories if cat['name'] == 'RenderQuality'):`
`    for setting in (set for set in category['settings'] if set['name'] == 'core:renderQuality'):`
`        ...`

2023-04-27 12:55 UTC, Vsevolod1983 commented
It looks like you should add definition to render settings schema.
I believe you need to add new render settings to this file:  pxr\imaging\rprUsd\schema.usda

Without that Maya cannot recognize type of newly added parameters and makes UI for these parameters with wrong type (like just plain string edit box instead of dropdown type).

2023-04-27 12:56 UTC, Vsevolod1983 requested changes
It looks like you should add definition to render settings schema.
I believe you need to add new render settings to this file: pxr\imaging\rprUsd\schema.usda

Without that Maya cannot recognize type of newly added parameters and makes UI for these parameters with wrong type (like just plain string edit box instead of dropdown type).

2023-04-28 10:08 UTC, Vsevolod1983 approved these changes

2023-04-28 17:49 UTC, merged