Add reservoir sampling setting
GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD pull request #695
Opened 2023-08-30 00:52 UTC by mixern6

### PURPOSE
Add reservoir sampling setting

2023-08-30 20:12 UTC, V-Gorash approved these changes

2023-08-31 00:23 UTC, bsavery commented on pxr/imaging/plugin/hdRpr/python/generateRenderSettingFiles.py
> +                ],
Sorry to be pedantic about help strings, but can we add an explanation of what this does with the "help" option?

2023-08-31 00:24 UTC, bsavery requested changes
Add help string

2023-08-31 08:59 UTC, s1lentssh approved these changes

2023-08-31 14:36 UTC, bsavery approved these changes

2023-08-31 14:36 UTC, merged